## sim parameters
dt_sim: 0.0001
dt_control: 0.01
controller_type: "Linear"
v_min : 0.5
w_max : 600
w_delta_lim: 50
accel : 3.5
deaccel : -28
wheel_radius : 0.025
robot_diameter : 0.095
y_std : 0.02
x_limit: 30


## motor parameters
motor_gain: 64.50
gain_mismatch: 0
motor_time_constant: 0.1
time_constant_mismatch: 0
measurement_bias: 0
measurement_std: 0
closed_loop_constant: 0.1
max_delta_u : 2
max_u: 11.1
kf_percentage: 0.66

## Classic Controllers Parameters
k_nlc : 3
b_smc : 1
gamma : 0.4
ktheta : 14.14
kd_theta : 2
td_y : 0.116
ki : 5

## PPO

ppo_w : 1
model_path : "model/PPO.zip"